site_name: Guia Podman
site_author: DevOps
site_url: https://ricardoandreh.github.io/guia-podman
repo_url: https://github.com/ricardoandreh/guia-podman
repo_name: ricardoandreh/guia-podman
copyright: Copyright &copy; 2025 DevOps
copyright_year: 2025
site_description: Guia de boas práticas para o Podman

theme:
  name: material
  favicon: public/favicon.ico
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: purple
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Instalação:
    - Visão Geral: installation/overview.md
  - Fundamentos:
    - Primeiros Passos: fundamentals/getting-started.md
    - Containers: fundamentals/containers.md
    - Imagens: fundamentals/images.md
  - Redes:
    - Redes no Podman: networking/network.md
    - Portas: networking/ports.md
  - Volumes:
    - Visão Geral: volumes/volumes.md
  - Avançado:
    - Segurança: advanced/security.md
    - Resolução de Problemas: advanced/troubleshooting.md
